language: python

python:
  - "3.4"

services: MySQL

sudo: required

env:
  - DB=mysql

before_install:
  - sudo apt-get update

# install dependencies
install:
  - pip install --upgrade pip
  - pip install coverage
  - sudo apt-get install python-numpy
  - "pip install -r dependencies.txt"
  - pip install git+https://github.com/multiplay/mysql-connector-python
  - python -m pip install requests
  - pip install djutils

before_script:
  - mysql -e 'create database myapp_test;'
  - python manage.py makemigrations
  - python manage.py syncdb
  - uname -a
  - printenv
  - pip3 --version
  - pip3 freeze
  - python3 --version
  - coverage3 --version
  - python3 -c "import numpy; print(numpy.__version__)"

script:
    - date
    - ls -al
    - touch IDB.log
    - ls -al
    - make test
    - ls -al
    - bash travis.bash
    - make check

# ignore push events to this branch
branches:
  only:
  - master
  - dev-branch
